name: evaluate-agent
on:
  workflow_dispatch:
jobs:
  dqn-evaluation:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-cd/eval-requirements.txt
      - name: Evaluate agent
        run: python ci-cd/evaluate.py
