name: evaluate-agent
on:
  workflow_dispatch:
jobs:
  dqn-evaluation:
    runs-on: ubuntu-latest
    env:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install OpenGL
        run: sudo apt-get install python-opengl
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -f https://download.pytorch.org/whl/torch_stable.html -r ci-cd/eval_requirements.txt
      - name: Evaluate agent
        run: xvfb-run -s "-screen 0 1400x900x24" python ci-cd/evaluate.py